# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'OAuth2Authorization' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Secrets

end

plugin 'cocoapods-keys', {
  :project => "org.groton.swift-examples.OAuth2Authorization",
  :keys => [
    "clientID",
    "clientSecret",
    "redirectURI"
  ]}

