# Uncomment the next line to define a global platform for your project
platform :ios, '17.0'

target 'Secrets' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Secrets

end

plugin 'cocoapods-keys', {
  :project => "org.groton.swift-examples.Secrets",
  :keys => [
    "secretOne",
    "SecretTwo",
    "SECRET_THREE"
  ]}

